
services:
  frontend:
    build:
      context: ./react_landing_page
      target: production
    depends_on:
      - api
    networks:
      - app-network

  api:
    build: ./python_chatbot_api
    expose:
      - "8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_TABLE_NAME=${SUPABASE_TABLE_NAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    networks:
      - app-network

  caddy:
    image: caddy:latest
    depends_on:
      - api
      - frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
