version: '3.8'

services:
  frontend:
    build: ./react_landing_page
    command: sh -c "npm run build"
    volumes:
      - frontend-dist:/app/dist
    networks:
      - app-network

  api:
    build: ./python_chatbot_api
    expose:
      - "8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - frontend-dist:/srv/frontend:ro
    networks:
      - app-network

volumes:
  frontend-dist:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
