version: '3.8'

services:
  frontend:
    build:
      context: ./react_landing_page
      target: production
    networks:
      - app-network

  api:
    build: ./python_chatbot_api
    expose:
      - "8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
